### ISSUE TITLE
Create driver for incompressible resistive MHD using mixed FE

### ISSUE THREAD

**Issue by jesusbonilla** [gridapapps/GridapMHD.jl#1]
We'll follow [1,2] and references therein (ref's to be completed) to implement the FE approximation of incompressible resistive MHD equations. As a first step we will focus on low Re & Ha numbers to avoid introducing stabilization terms. We'll follow [1] to implement mixed FE. 

Following the formulation in [1], the discrete problem reads: find <img src="http://latex.codecogs.com/gif.latex?(\boldsymbol{u},\boldsymbol{E},\boldsymbol{B})\in%20H^h(\mathrm{grad},\Omega)\times%20H^h(\mathrm{curl},\Omega)%20\times%20H^h(\mathrm{div},\Omega)"> and <img src="http://latex.codecogs.com/gif.latex?p\in%20Q"> such that for any <img src="http://latex.codecogs.com/gif.latex?(\boldsymbol{v},\boldsymbol{F},\boldsymbol{C})\in%20H^h(\mathrm{grad},\Omega)\times%20H^h(\mathrm{curl},\Omega)%20\times%20H^h(\mathrm{div},\Omega)"> and <img src="http://latex.codecogs.com/gif.latex?q\in%20Q"> it holds

<p align=center>
<img src="http://latex.codecogs.com/gif.latex?\begin{aligned}%20\left(\frac{\partial%20\boldsymbol{u}}{\partial%20t}\right)%20+%20\frac{1}{2}\left[(\boldsymbol{u}\cdot\nabla%20\boldsymbol{u},%20\boldsymbol{v})%20-%20(\boldsymbol{u}\cdot\nabla%20\boldsymbol{v},%20\boldsymbol{u})\right]%20+%20\frac{1}{Re}(\nabla%20\boldsymbol{u},\nabla%20\boldsymbol{v})%20-%20S(\boldsymbol{j}\times%20\boldsymbol{B},%20\boldsymbol{v})%20-%20(p,\nabla\cdot%20\boldsymbol{v})%20&=%20(\boldsymbol{f},%20\boldsymbol{v}),%20\\%20(\boldsymbol{j},\boldsymbol{F})%20-%20\frac{1}{Rm}(\boldsymbol{B},\nabla\times%20\boldsymbol{F})%20&=%200,%20\\%20\left(\frac{\partial%20\boldsymbol{B}}{\partial%20t},%20\boldsymbol{C}\right)%20+%20(\nabla\times%20\boldsymbol{E},%20\boldsymbol{C})%20&=%200,%20\\%20(\nabla\cdot%20\boldsymbol{u},%20q)&=%200,%20\end{aligned}">
</p>

where <img src="http://latex.codecogs.com/gif.latex?\boldsymbol{j}%20=%20\boldsymbol{E}%20+%20\boldsymbol{u}\times\boldsymbol{B}">.

Discretizing above equations with implicit Euler results in exact satisfaction of the Gauss low for every time step, this follows from [Thm 1, 1]. In [Sect. 3.4, 1] explicit Picard and Newton formulations can be found. 

### Tasks
- [x] Create a Julia project/driver for incompressible MHD equations.
- [x] Implement above formulation using Gridap library.
- [x] Implement Shercliff's benchmark test (See [Sec. 5.A, 2] for analytical solution).
- [x] Implement Hunt's benchmark test (See [Sec. 5.B, 2] for analytical solution).
- [ ] Implement 2D island coalescence problem (a.k.a. reconnection problem?).

### References
[1] K. Hu, Y. Ma & J. Xu  [_Stable Finite Element Methods Preserving ∇ · B = 0 Exactly for MHD Models_](https://arxiv.org/pdf/1410.1095.pdf) Numerische Mathematik,  **135**, 371–396 (2017)
[2] R. Planas [_STABILIZED FINITE ELEMENT FORMULATIONS FOR SOLVING INCOMPRESSIBLE
MAGNETOHYDRODYNAMICS_](https://deca.upc.edu/en/people/ramon.codina/files/about/ramonplanas.pdf) PhD Thesis (2013)
